### ISSUE TITLE
Drag and Drop Should Copy

### ISSUE THREAD

**Issue by marwan-at-work** [tailscale-dev/vscode-tailscale#229] opened 2023-09-19 18:59 UTC
Drang and drop should copy files, and not move them. Maybe a setting can also let the user choose

**Comment by samlinville** [comment] 2023-09-19 20:48
Closing as duplicate of https://github.com/tailscale-dev/vscode-tailscale/issues/201

**Closed by samlinville** 2023-09-19 20:48 UTC
